[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/*.log
    Tag               enterprise.*
    Read_from_Head   true
    Refresh_Interval  1

[OUTPUT]
    Name              kafka
    Match             *
    Brokers           kafka:9092
    Format            json 
    Topics            enterprise-logs