services:

  log-generator:
    build:
      context: ../services/log-generator
    volumes:
      - log-data:/logs

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:4.1
    volumes:
      - log-data:/logs:ro
      - ../config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    depends_on:
      - log-generator

volumes:
  log-data: