name: Docker Services CD

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Log Consumer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/log-consumer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/log-consumer:latest,${{ secrets.DOCKERHUB_USERNAME }}/log-consumer:v1.0

      - name: Build and Push Log Generator
        uses: docker/build-push-action@v5
        with:
          context: services/log-generator
          file: services/log-generator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/log-generator:latest,${{ secrets.DOCKERHUB_USERNAME }}/log-generator:v1.0
