name: Helm Chart CD

on:
  push:
    branches:
      - main
    paths:
      - 'infra/helm/**'

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by chart-releaser

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: infra/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
